name: JOER Server

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  eslint-check:
    name: ESLint checking
    runs-on: ubuntu-latest
    steps:
      - name: Moving to repository root
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setuping Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm

      - name: Installing dependecies
        run: npm ci

      - name: Linting files
        run: npm run affected:lint -- --base="origin/${GITHUB_BASE_REF}" --head=HEAD

  run-tests:
    name: Jest tests
    needs: 
      - eslint-check
    runs-on: ubuntu-latest
    env:
      ENV_BACKEND_STORAGE: ${{ secrets.ENV_BACKEND_STORAGE }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: joer_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Moving to repository root
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setuping Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: npm

      - name: Installing dependecies
        run: npm ci

      - name: Setup env
        run: |
          echo "$ENV_BACKEND_STORAGE" | base64 -d > ./apps/server/.env

      - name:  Run migrations
        run: |
          npm run migration-test server

      - name: Testing affected files
        run: npm run affected:test -- --base="origin/${GITHUB_BASE_REF}" --head=HEAD
